version: '3'

services:
  homestead:
    image: mariadb:10.6.4-focal
    container_name: homestead
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    image: phpmyadmin:5-fpm-alpine
    ports:
      - "8083:80"
    depends_on:
      - homestead
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./blog/:/usr/share/nginx/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
    depends_on:
      - php-fpm
      - homestead
  php-fpm:
    image: php:8.0-fpm
    container_name: php
    restart: always
    volumes:
      - ./blog/:/usr/share/nginx/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - homestead